[build]
  command = "cd client && npm run build"
  publish = "client/dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  NPM_FLAGS = "--legacy-peer-deps"

# API routes for serverless functions
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Domain redirects
[[redirects]]
  from = "https://www.mysticarcana.com/*"
  to = "/"
  status = 301
  force = true

[[redirects]]
  from = "https://mysticarcana.netlify.app/*"
  to = "/"
  status = 301
  force = true

# Handle SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[dev]
  command = "cd client && npm run dev"
  # Use dynamic port - Netlify will find an available one
  autoLaunch = true
  # The targetPort should match the default in vite.config.ts
  targetPort = 3000
  publish = "client/dist"

# Function bundle settings
[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@supabase/supabase-js"]

[dev.functions]
  directory = "netlify/functions"

[dev.edge_functions]
  directory = "netlify/edge-functions"
